export const hotels = [
  {
    id: 1,
    name: "The Jungle Canopy Resort",
    location: "Bali, Indonesia",
    price: 189,
    rating: 4.9,
    reviews: 1240,
    tag: "Bestseller",
    img: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80",
    amenities: ["🏊 Pool", "🌿 Spa", "🍃 Garden", "🌅 View"],
    desc: "Nestled among ancient banyan trees, this award-winning eco-resort blends seamlessly into Bali's lush landscape. Experience world-class hospitality in a setting that celebrates the natural world around you. Each room is crafted with local materials and thoughtfully designed for maximum comfort and sustainability.",
  },
  {
    id: 2,
    name: "Emerald Bay Lodge",
    location: "Maldives",
    price: 320,
    rating: 4.8,
    reviews: 876,
    tag: "Luxury",
    img: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=600&q=80",
    amenities: ["🤿 Diving", "🏝 Private Beach", "🍹 Bar", "🛥 Transfers"],
    desc: "Overwater bungalows surrounded by crystal-clear turquoise lagoons with direct ocean access. Indulge in the ultimate Maldivian experience with private plunge pools and butler service included in every stay.",
  },
  {
    id: 3,
    name: "Green Peak Sanctuary",
    location: "Kerala, India",
    price: 95,
    rating: 4.7,
    reviews: 2103,
    tag: "Eco-Friendly",
    img: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
    amenities: ["🧘 Yoga", "🌿 Ayurveda", "🍃 Organic", "🏞 Trails"],
    desc: "An Ayurvedic sanctuary in the Western Ghats, surrounded by spice plantations and misty mountain air. Reconnect with nature through daily yoga, traditional treatments, and farm-to-table organic cuisine.",
  },
  {
    id: 4,
    name: "Tulum Treehouse Hotel",
    location: "Tulum, Mexico",
    price: 145,
    rating: 4.6,
    reviews: 932,
    tag: "Trending",
    img: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
    amenities: ["🌴 Jungle", "🌊 Cenote", "🍽 Restaurant", "📶 WiFi"],
    desc: "Bohemian treehouse suites above the Mayan jungle, minutes from turquoise cenotes and white-sand beaches. Each suite is a hand-crafted masterpiece blending rustic charm with modern luxury.",
  },
  {
    id: 5,
    name: "Rainforest Retreat",
    location: "Costa Rica",
    price: 210,
    rating: 4.9,
    reviews: 654,
    tag: "Top Rated",
    img: "https://images.unsplash.com/photo-1439130490301-25e322d88054?w=600&q=80",
    amenities: ["🦜 Wildlife", "♾ Infinity Pool", "🌿 Organic", "🚶 Hiking"],
    desc: "An intimate retreat perched above the treetops of Costa Rica's biodiverse cloud forest. Wake up to the calls of toucans and howler monkeys as morning mist rolls through the canopy below.",
  },
  {
    id: 6,
    name: "Serenity Islands Resort",
    location: "Phuket, Thailand",
    price: 175,
    rating: 4.7,
    reviews: 1567,
    tag: "Family Pick",
    img: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=600&q=80",
    amenities: ["🏊 Kids Pool", "🏖 Beach", "🎭 Entertainment", "🍜 Dining"],
    desc: "A family paradise with vibrant tropical gardens, kids clubs, and Thailand's most stunning sunsets. Our award-winning kids club and dedicated family butler ensure stress-free tropical bliss.",
  },
];

export const destinations = [
  {
    name: "Bali",
    country: "Indonesia",
    hotels: 1240,
    img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&q=80",
  },
  {
    name: "Maldives",
    country: "Indian Ocean",
    hotels: 380,
    img: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=400&q=80",
  },
  {
    name: "Kerala",
    country: "India",
    hotels: 720,
    img: "https://images.unsplash.com/photo-1609920658906-8223bd289001?w=400&q=80",
  },
  {
    name: "Phuket",
    country: "Thailand",
    hotels: 930,
    img: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=400&q=80",
  },
];
